name: Docker Image CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    env:
      # 定义镜像标签，为"commit id"
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker imag
        run: docker build . --file Dockerfile --tag ${{ secrets.REPOSITORY }}:${{ env.IMAGE_TAG }}
      - name: Login to Registry
        run: echo "${{ secrets.REPOSITORY_PASSWORD }}" | docker login -u "${{ secrets.REPOSITORY_USERNAME }}" --password-stdin ${{ secrets.REGISTRY }}
      - name: Push the Docker image
        run: docker push ${{ secrets.REPOSITORY }}:${{ env.IMAGE_TAG }}
