name: Docker Image CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker imag
        run: docker build . --file Dockerfile --tag ${{ secrets.REPOSITORY }}:$(date +%s)
      - name: Login to Registry
        run: echo "${{ secrets.REPOSITORY_PASSWORD }}" | docker login -u "${{ secrets.REPOSITORY_USERNAME }}" --password-stdin ${{ secrets.REGISTRY }}
      - name: Push the Docker image
        run: docker push ${{ secrets.REPOSITORY }}:$(date +%s)

